"""remove join_code from campaign

Revision ID: c4a23ddc0287
Revises: 0018_roll_event_user_id
Create Date: 2026-03-04 01:18:26.438541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a23ddc0287'
down_revision: Union[str, None] = '0018_roll_event_user_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_join_code', table_name='campaign')
    op.drop_column('campaign', 'join_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('join_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_campaign_join_code', 'campaign', ['join_code'], unique=True)
    # ### end Alembic commands ###
