import {
  BaseItemArmorCategory,
  BaseItemKind,
  type BaseItem,
} from "../../../entities/base-item";
import { CampaignSystemType } from "../../../entities/campaign";

const makeBaseItem = (
  overrides: Partial<BaseItem> & Pick<BaseItem, "id" | "canonicalKey" | "nameEn" | "namePt" | "itemKind">,
): BaseItem => ({
  system: CampaignSystemType.DND5E,
  descriptionEn: null,
  descriptionPt: null,
  equipmentCategory: null,
  costQuantity: null,
  costUnit: null,
  weight: 0,
  weaponCategory: null,
  weaponRangeType: null,
  damageDice: null,
  damageType: null,
  rangeNormalMeters: null,
  rangeLongMeters: null,
  versatileDamage: null,
  weaponPropertiesJson: null,
  armorCategory: null,
  armorClassBase: null,
  dexBonusRule: null,
  strengthRequirement: null,
  stealthDisadvantage: null,
  isShield: false,
  source: null,
  sourceRef: null,
  isSrd: false,
  isActive: true,
  aliases: [],
  ...overrides,
});

export const TEST_CREATION_BASE_ITEMS: BaseItem[] = [
  makeBaseItem({ id: "base-spellbook", canonicalKey: "spellbook", nameEn: "Spellbook", namePt: "Grimório", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-quarterstaff", canonicalKey: "quarterstaff", nameEn: "Quarterstaff", namePt: "Cajado", itemKind: BaseItemKind.WEAPON, weight: 4 }),
  makeBaseItem({ id: "base-component-pouch", canonicalKey: "component_pouch", nameEn: "Component Pouch", namePt: "Bolsa de Componentes", itemKind: BaseItemKind.FOCUS }),
  makeBaseItem({ id: "base-scholars-pack", canonicalKey: "scholars_pack", nameEn: "Scholar's Pack", namePt: "Mochila do Estudioso", itemKind: BaseItemKind.PACK }),
  makeBaseItem({ id: "base-prayer-book", canonicalKey: "prayer_book", nameEn: "Prayer book", namePt: "Livro de Orações", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-common-clothes", canonicalKey: "common_clothes", nameEn: "Common clothes", namePt: "Roupas Comuns", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-fine-clothes", canonicalKey: "fine_clothes", nameEn: "Fine clothes", namePt: "Roupas Finas", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-travelers-clothes", canonicalKey: "travelers_clothes", nameEn: "Traveler's clothes", namePt: "Roupas de Viagem", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-scroll-case", canonicalKey: "scroll_case", nameEn: "Scroll case", namePt: "Estojo de Pergaminho", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-winter-blanket", canonicalKey: "winter_blanket", nameEn: "Winter blanket", namePt: "Cobertor de Inverno", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-shovel", canonicalKey: "shovel", nameEn: "Shovel", namePt: "Pá", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-iron-pot", canonicalKey: "iron_pot", nameEn: "Iron pot", namePt: "Panela de Ferro", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-letter-of-introduction", canonicalKey: "letter_of_introduction", nameEn: "Letter of introduction", namePt: "Carta de Introdução", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-crowbar", canonicalKey: "crowbar", nameEn: "Crowbar", namePt: "Pé de Cabra", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-costume", canonicalKey: "costume", nameEn: "Costume", namePt: "Fantasia", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-incense", canonicalKey: "incense", nameEn: "Incense", namePt: "Incenso", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-vestments", canonicalKey: "vestments", nameEn: "Vestments", namePt: "Vestes Litúrgicas", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-dark-common-clothes", canonicalKey: "dark_common_clothes_with_hood", nameEn: "Dark common clothes with hood", namePt: "Roupas Comuns Escuras com Capuz", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-favor", canonicalKey: "favor_of_an_admirer", nameEn: "Favor of an admirer", namePt: "Lembrança de um Admirador", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-signet-ring", canonicalKey: "signet_ring", nameEn: "Signet ring", namePt: "Anel de Sinete", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-scroll-of-pedigree", canonicalKey: "scroll_of_pedigree", nameEn: "Scroll of pedigree", namePt: "Pergaminho de Linhagem", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-hunting-trap", canonicalKey: "hunting_trap", nameEn: "Hunting trap", namePt: "Armadilha de Caça", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-animal-trophy", canonicalKey: "animal_trophy", nameEn: "Animal trophy", namePt: "Troféu Animal", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-ink", canonicalKey: "bottle_of_black_ink", nameEn: "Bottle of black ink", namePt: "Frasco de Tinta Preta", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-quill", canonicalKey: "quill", nameEn: "Quill", namePt: "Pena de Escrita", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-small-knife", canonicalKey: "small_knife", nameEn: "Small knife", namePt: "Faca Pequena", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-unanswered-letter", canonicalKey: "letter_with_unanswered_question", nameEn: "Letter with unanswered question", namePt: "Carta com Pergunta sem Resposta", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-belaying-pin", canonicalKey: "belaying_pin", nameEn: "Belaying pin", namePt: "Pino de Amarração", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-silk-rope", canonicalKey: "silk_rope", nameEn: "Silk Rope", namePt: "Corda de Seda", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-lucky-charm", canonicalKey: "lucky_charm", nameEn: "Lucky charm", namePt: "Amuleto da Sorte", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-insignia", canonicalKey: "insignia_of_rank", nameEn: "Insignia of rank", namePt: "Insígnia de Patente", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-fallen-enemy-trophy", canonicalKey: "trophy_from_fallen_enemy", nameEn: "Trophy from fallen enemy", namePt: "Troféu de Inimigo Derrotado", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-home-city-map", canonicalKey: "map_of_home_city", nameEn: "Map of home city", namePt: "Mapa da Cidade Natal", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-pet-mouse", canonicalKey: "pet_mouse", nameEn: "Pet mouse", namePt: "Rato de Estimação", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-parent-token", canonicalKey: "token_from_parent", nameEn: "Token from parent", namePt: "Lembrança dos Pais", itemKind: BaseItemKind.GEAR }),
  makeBaseItem({ id: "base-shield", canonicalKey: "shield", nameEn: "Shield", namePt: "Escudo", itemKind: BaseItemKind.ARMOR, armorCategory: BaseItemArmorCategory.SHIELD, armorClassBase: 2, isShield: true }),
  makeBaseItem({ id: "base-holy-symbol", canonicalKey: "holy_symbol", nameEn: "Holy Symbol", namePt: "Símbolo Sagrado", itemKind: BaseItemKind.FOCUS }),
  makeBaseItem({ id: "base-mace", canonicalKey: "mace", nameEn: "Mace", namePt: "Maça", itemKind: BaseItemKind.WEAPON, weight: 4 }),
  makeBaseItem({ id: "base-warhammer", canonicalKey: "warhammer", nameEn: "Warhammer", namePt: "Martelo de Guerra", itemKind: BaseItemKind.WEAPON, weight: 2 }),
  makeBaseItem({ id: "base-scale-mail", canonicalKey: "scale_mail", nameEn: "Scale Mail", namePt: "Brunea", itemKind: BaseItemKind.ARMOR, armorCategory: BaseItemArmorCategory.MEDIUM, armorClassBase: 14, dexBonusRule: "max_2", weight: 45 }),
  makeBaseItem({ id: "base-chain-mail", canonicalKey: "chain_mail", nameEn: "Chain Mail", namePt: "Cota de Malha", itemKind: BaseItemKind.ARMOR, armorCategory: BaseItemArmorCategory.HEAVY, armorClassBase: 16, dexBonusRule: "none", weight: 55 }),
  makeBaseItem({ id: "base-leather", canonicalKey: "leather", nameEn: "Leather", namePt: "Couro", itemKind: BaseItemKind.ARMOR, armorCategory: BaseItemArmorCategory.LIGHT, armorClassBase: 11, weight: 10 }),
  makeBaseItem({ id: "base-light-crossbow", canonicalKey: "light_crossbow", nameEn: "Light Crossbow", namePt: "Besta Leve", itemKind: BaseItemKind.WEAPON, weight: 5 }),
  makeBaseItem({ id: "base-crossbow-bolt", canonicalKey: "crossbow_bolt", nameEn: "Crossbow bolt", namePt: "Virote", itemKind: BaseItemKind.AMMO, weight: 0.075 }),
  makeBaseItem({ id: "base-priests-pack", canonicalKey: "priests_pack", nameEn: "Priest's Pack", namePt: "Mochila do Sacerdote", itemKind: BaseItemKind.PACK }),
  makeBaseItem({ id: "base-druidic-focus", canonicalKey: "druidic_focus", nameEn: "Druidic Focus", namePt: "Foco Druídico", itemKind: BaseItemKind.FOCUS }),
  makeBaseItem({ id: "base-scimitar", canonicalKey: "scimitar", nameEn: "Scimitar", namePt: "Cimitarra", itemKind: BaseItemKind.WEAPON, weight: 3 }),
  makeBaseItem({ id: "base-shortsword", canonicalKey: "shortsword", nameEn: "Shortsword", namePt: "Espada Curta", itemKind: BaseItemKind.WEAPON, weight: 2 }),
  makeBaseItem({ id: "base-forgery-kit", canonicalKey: "forgery_kit", nameEn: "Forgery Kit", namePt: "Kit de Falsificação", itemKind: BaseItemKind.TOOL }),
  makeBaseItem({ id: "base-disguise-kit", canonicalKey: "disguise_kit", nameEn: "Disguise Kit", namePt: "Kit de Disfarce", itemKind: BaseItemKind.TOOL }),
  makeBaseItem({ id: "base-musical-instrument", canonicalKey: "musical_instrument", nameEn: "Musical Instrument", namePt: "Instrumento Musical", itemKind: BaseItemKind.TOOL }),
  makeBaseItem({ id: "base-artisans-tools", canonicalKey: "artisans_tools", nameEn: "Artisan's Tools", namePt: "Ferramentas de Artesão", itemKind: BaseItemKind.TOOL }),
  makeBaseItem({ id: "base-herbalism-kit", canonicalKey: "herbalism_kit", nameEn: "Herbalism Kit", namePt: "Kit de Herbalismo", itemKind: BaseItemKind.TOOL }),
  makeBaseItem({ id: "base-gaming-set", canonicalKey: "gaming_set", nameEn: "Gaming Set", namePt: "Jogo de Mesa", itemKind: BaseItemKind.TOOL }),
];
