"""Add CombatState table

Revision ID: 563684764260
Revises: 0031_realtime_combat_log
Create Date: 2026-03-22 00:16:59.230274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '563684764260'
down_revision: Union[str, None] = '0031_realtime_combat_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_state',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sa.Enum('initiative', 'active', 'ended', name='combat_phase_enum'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn_index', sa.Integer(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['campaign_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_state_session_id'), 'combat_state', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combat_state_session_id'), table_name='combat_state')
    op.drop_table('combat_state')
    op.execute("DROP TYPE IF EXISTS combat_phase_enum")
    # ### end Alembic commands ###
