"""remove join_code

Revision ID: 57d7e3a6b345
Revises: 0016_party_member_left
Create Date: 2026-02-23 00:34:17.424252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57d7e3a6b345'
down_revision: Union[str, None] = '0016_party_member_left'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_campaign_join_code', 'campaign', type_='unique')
    op.drop_constraint('campaign_member_campaign_id_fkey', 'campaign_member', type_='foreignkey')
    op.drop_constraint('campaign_member_user_id_fkey', 'campaign_member', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_member', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'campaign_member', 'app_user', ['user_id'], ['id'])
    op.drop_index('ix_campaign_session_join_code', table_name='campaign_session')
    op.drop_constraint('campaign_session_campaign_id_fkey', 'campaign_session', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_session', 'party', ['party_id'], ['id'])
    op.create_foreign_key(None, 'campaign_session', 'campaign', ['campaign_id'], ['id'])
    op.drop_column('campaign_session', 'join_code')
    op.drop_constraint('inventoryitem_member_id_fkey', 'inventoryitem', type_='foreignkey')
    op.drop_constraint('inventoryitem_campaign_id_fkey', 'inventoryitem', type_='foreignkey')
    op.drop_constraint('inventoryitem_item_id_fkey', 'inventoryitem', type_='foreignkey')
    op.create_foreign_key(None, 'inventoryitem', 'campaign_member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'inventoryitem', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'inventoryitem', 'item', ['item_id'], ['id'])
    op.drop_constraint('item_campaign_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'campaign', ['campaign_id'], ['id'])
    op.drop_constraint('npc_campaign_id_fkey', 'npc', type_='foreignkey')
    op.create_foreign_key(None, 'npc', 'campaign', ['campaign_id'], ['id'])
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=False)
    op.drop_constraint('preferences_user_id_fkey', 'preferences', type_='foreignkey')
    op.create_foreign_key(None, 'preferences', 'app_user', ['user_id'], ['id'])
    op.alter_column('roll_event', 'campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roll_event', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint('fk_roll_event_session_id', 'roll_event', type_='foreignkey')
    op.drop_constraint('roll_event_campaign_id_fkey', 'roll_event', type_='foreignkey')
    op.create_foreign_key(None, 'roll_event', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'roll_event', 'campaign_session', ['session_id'], ['id'])
    op.alter_column('session_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('session_state_session_id_fkey', 'session_state', type_='foreignkey')
    op.drop_constraint('session_state_player_user_id_fkey', 'session_state', type_='foreignkey')
    op.create_foreign_key(None, 'session_state', 'app_user', ['player_user_id'], ['id'])
    op.create_foreign_key(None, 'session_state', 'campaign_session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_state', type_='foreignkey')
    op.drop_constraint(None, 'session_state', type_='foreignkey')
    op.create_foreign_key('session_state_player_user_id_fkey', 'session_state', 'app_user', ['player_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('session_state_session_id_fkey', 'session_state', 'campaign_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('session_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'roll_event', type_='foreignkey')
    op.drop_constraint(None, 'roll_event', type_='foreignkey')
    op.create_foreign_key('roll_event_campaign_id_fkey', 'roll_event', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_roll_event_session_id', 'roll_event', 'campaign_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('roll_event', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('roll_event', 'campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'preferences', type_='foreignkey')
    op.create_foreign_key('preferences_user_id_fkey', 'preferences', 'app_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_constraint(None, 'npc', type_='foreignkey')
    op.create_foreign_key('npc_campaign_id_fkey', 'npc', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_campaign_id_fkey', 'item', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.create_foreign_key('inventoryitem_item_id_fkey', 'inventoryitem', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('inventoryitem_campaign_id_fkey', 'inventoryitem', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('inventoryitem_member_id_fkey', 'inventoryitem', 'campaign_member', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaign_session', sa.Column('join_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaign_session', type_='foreignkey')
    op.drop_constraint(None, 'campaign_session', type_='foreignkey')
    op.create_foreign_key('campaign_session_campaign_id_fkey', 'campaign_session', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_campaign_session_join_code', 'campaign_session', ['join_code'], unique=True)
    op.drop_constraint(None, 'campaign_member', type_='foreignkey')
    op.drop_constraint(None, 'campaign_member', type_='foreignkey')
    op.create_foreign_key('campaign_member_user_id_fkey', 'campaign_member', 'app_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('campaign_member_campaign_id_fkey', 'campaign_member', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_campaign_join_code', 'campaign', ['join_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
