import { normalizeBackgroundId } from "../data/backgrounds";
import type { CreationPersonalityFields } from "./creationPersonality";

export type CreationRandomizableField = keyof CreationPersonalityFields;

type BackgroundRandomTable = Partial<Record<CreationRandomizableField, string[]>>;

const BACKGROUND_RANDOM_TABLES: Partial<Record<string, BackgroundRandomTable>> = {
  acolyte: {
    personalityTraits: [
      "Eu idolatro um herói particular da minha fé, e constantemente me refiro a seus feitos e exemplos.",
      "Eu consigo encontrar semelhanças mesmo entre os inimigos mais violentos, com empatia e sempre trabalhando pela paz.",
      "Eu vejo presságios em cada evento e ação. Os deuses estão falando conosco, nós apenas temos de ouvi-los.",
      "Nada pode abalar minha atitude otimista.",
      "Eu cito (corretamente ou não) textos sagrados e provérbios em quase qualquer situação.",
      "Eu sou tolerante (ou intolerante) a qualquer outra fé, e respeito (ou condeno) a adoração a outros deuses.",
      "Eu aprecio comida requintada, bebidas e a elite entre o alto escalão de meu templo. Uma vida dura me irrita.",
      "Eu passei tanto tempo no templo que possuo pouca prática em lidar com as pessoas mundo a fora.",
    ],
    ideals: [
      "Tradição. As tradições ancestrais de adoração e sacrifício devem ser preservadas e perpetradas. (Leal)",
      "Caridade. Eu sempre tento ajudar aqueles em necessidade, não importando o custo pessoal. (Bom)",
      "Mudança. Nós devemos ajudar a conduzir as mudanças que os deuses estão constantemente trabalhando para o mundo. (Caótico)",
      "Poder. Eu espero que um dia eu consiga chegar ao topo na hierarquia da minha religião. (Leal)",
      "Fé. Eu acredito que minha divindade guia minhas ações. Eu tenho fé que, se eu trabalhar duro, coisas boas acontecerão. (Leal)",
      "Aspiração. Eu busco ser digno da graça do meu deus ao corresponder minhas ações aos seus ensinamentos. (Qualquer)",
    ],
    bonds: [
      "Eu morreria para recuperar uma relíquia ancestral de minha fé, perdida há muito tempo.",
      "Eu ainda terei minha vingança contra o templo corrupto que me acusou de heresia.",
      "Eu devo minha vida ao sacerdote que me acolheu quando meus pais morreram.",
      "Tudo o que faço, faço pelo povo.",
      "Eu farei qualquer coisa para proteger o templo que sirvo.",
      "Eu busco guardar um texto sagrado que meus inimigos dizem ser herético e tentam destruí-lo.",
    ],
    flaws: [
      "Eu julgo os outros severamente, e a mim mesmo mais ainda.",
      "Eu deposito muita confiança naqueles que detêm o poder na hierarquia de meu templo.",
      "Minha devoção é muitas vezes me cega perante aqueles que professam a fé do meu deus.",
      "Meu pensamento é inflexível.",
      "Eu suspeito de estranhos e sempre espero o pior deles.",
      "Depois de escolher um objetivo, eu fico obcecado em cumpri-lo, até mesmo em detrimento de qualquer outra coisa em minha vida.",
    ],
  },
  charlatan: {
    personalityTraits: [
      "Apaixono-me facilmente e estou sempre cortejando alguém.",
      "Tenho uma piada para qualquer ocasião, especialmente as inadequadas.",
      "Bajulação é meu método favorito para conseguir o que quero.",
      "Sou um apostador nato e adoro correr riscos.",
      "Minto sobre quase tudo, mesmo sem motivo.",
      "Sarcasmo e insultos são minhas armas preferidas.",
      "Carrego vários símbolos sagrados e invoco o deus que mais me convém no momento.",
      "Pego discretamente qualquer coisa que pareça ter algum valor.",
    ],
    ideals: [
      "Independência.",
      "Justiça.",
      "Caridade.",
      "Criatividade.",
      "Amizade.",
      "Aspiração.",
    ],
    bonds: [
      "Enganei a pessoa errada e preciso evitar encontrá-la novamente.",
      "Devo tudo ao meu mentor, um sujeito terrível.",
      "Tenho um filho em algum lugar que não me conhece.",
      "Quero recuperar o título e as terras da minha família.",
      "Alguém poderoso matou quem eu amava.",
      "Arruínei uma pessoa inocente e busco redenção.",
    ],
    flaws: [
      "Não resisto a um rosto bonito.",
      "Estou sempre endividado.",
      "Acredito que ninguém pode me enganar.",
      "Sou ganancioso demais.",
      "Não resisto a enganar pessoas poderosas.",
      "Fujo quando a situação fica realmente perigosa.",
    ],
  },
  criminal: {
    personalityTraits: [
      "Eu sempre tenho um plano para quando as coisas derem errado.",
      "Sou calmo diante de qualquer situação. Nunca levanto a voz ou deixo minhas emoções me controlarem.",
      "A primeira coisa que faço quando entro em um lugar é notar onde estão as saídas e onde as riquezas estão guardadas.",
      "Eu prefiro fazer um novo amigo a um novo inimigo.",
      "Eu mudo de ideia ou de humor tão rápido quanto um batedor de carteiras muda de calçada.",
      "Eu não gasto meu tempo com pessoas que não podem me ser úteis.",
      "Eu sou incrivelmente charmoso e uso isso para conseguir o que quero.",
      "Eu guardo segredos muito bem e nunca confio plenamente em ninguém.",
    ],
    ideals: [
      "Honra: Eu não roubo de outros ladrões ou de quem precisa mais do que eu. (Leal)",
      "Liberdade: Correntes foram feitas para serem quebradas, assim como as leis que tentam nos prender. (Caotico)",
      "Caridade: Eu roubo dos ricos para dar aos necessitados, ou pelo menos para aqueles que eu gosto. (Bom)",
      "Ganancia: Eu farei o que for preciso para ficar rico, não importa quem saia prejudicado. (Mau)",
      "Poder: O crime é apenas uma ferramenta para eu alcançar o topo e ditar as regras. (Neutro)",
      "Redencao: Há uma parte de mi que quer deixar essa vida para trás e provar que posso ser alguém melhor. (Qualquer)",
    ],
    bonds: [
      "Eu tenho uma dívida enorme com um chefe do crime que precisa ser paga logo.",
      "Meus antigos parceiros de crime me traíram, e eu vou ter minha vingança custe o que custar.",
      "Tudo o que eu faço é para garantir um futuro melhor para a minha família ou para alguém que amo.",
      "Um inocente foi preso por um crime que EU cometi. Minha consciência pesa por causa disso.",
      "Eu compartilho meus ganhos com o orfanato ou a comunidade carente que me acolheu quando eu não tinha nada.",
      "Alguém do meu passado que eu respeito muito (um mentor ou parceiro) sumiu, e eu preciso descobrir o que aconteceu.",
    ],
    flaws: [
      "Quando vejo algo valioso, não consigo evitar o impulso de tentar roubar.",
      "Eu prefiro inventar uma mentira elaborada a dizer a verdade, mesmo quando a verdade seria mais simples.",
      "Eu sou covarde. Se as coisas ficarem feias no combate, minha primeira reação é correr e me salvar.",
      "Eu tenho um rancor profundo e duradouro; nunca esqueço uma ofensa, por menor que seja.",
      "Eu subestimo as autoridades e o perigo, achando que sou esperto demais para ser pego.",
      "Se houver um botão, uma alavanca ou um cofre trancado, eu PRECISO mexer nele, mesmo sabendo que pode ser uma armadilha.",
    ],
  },
  entertainer: {
    personalityTraits: [
      "Eu sei como cativar uma multidao e posso entreter as pessoas por horas.",
      "Eu amo ser o centro das atencoes e nao suporto ser ignorado.",
      "Eu me sinto desconfortavel se nao puder me vestir com roupas chamativas ou expressar minha arte.",
      "Eu sou muito dramatico e mudo de humor dependendo da reacao do meu publico.",
      "Eu mudo de assunto ou conto uma piada sempre que a conversa fica muito seria ou tensa.",
      "Eu adoro ouvir uma boa historia, mas prefiro ainda mais contar a minha versao dela.",
      "Eu sou extremamente perfeccionista com a minha arte e exijo o maximo de mim mesmo.",
      "Eu sou muito facil de lidar e faco amigos rapidamente em qualquer taverna ou salao.",
    ],
    ideals: [
      "Beleza: A arte e a expressao da beleza sao as coisas mais importantes do mundo. (Bom)",
      "Tradicao: As historias e as musicas do passado devem ser preservadas e protegidas a todo custo. (Leal)",
      "Criatividade: A arte deve desafiar as regras e quebrar os padroes estabelecidos. (Caotico)",
      "Ganancia: Eu uso meu talento para conseguir dinheiro, fama e uma vida de luxo. (Mau)",
      "Povo: Minha arte pertence ao povo, nao aos nobres; eu toco para alegrar os oprimidos. (Neutro)",
      "Identidade: Eu busco a perfeicao na minha arte para provar o meu proprio valor e ser lembrado para sempre. (Qualquer)",
    ],
    bonds: [
      "Eu farei qualquer coisa para salvar o teatro, circo ou trupe de artistas que me acolheu e me ensinou tudo.",
      "Minha fada madrinha, mentor ou antigo mestre me deu meu instrumento/ferramenta, e ele e o meu bem mais precioso.",
      "Eu estou perseguindo uma cancao, historia ou lenda perdida que pode me dar a fama definitiva.",
      "Eu cometi um erro no passado que arruinou a reputacao de um inocente, e agora quero me redimir atraves da minha arte.",
      "Eu tenho um rival artistico que tenta me sabotar a cada esquina, e eu preciso provar que sou melhor que ele.",
      "Eu toco ou atuo para mandar dinheiro para alguem que amo e que ficou para tras na minha terra natal.",
    ],
    flaws: [
      "Eu nao consigo resistir aos prazeres da carne, especialmente vinho, boa comida e apostas.",
      "Uma vez que alguem me critica ou fala mal da minha arte, eu me torno obsessivo em me vingar ou provar que a pessoa esta errada.",
      "Eu sou incrivelmente arrogante e secretamente acredito que todos ao meu redor sao inferiores ou sem cultura.",
      "Eu entro em panico se eu nao for o centro das atencoes ou se as pessoas pararem de olhar para mim.",
      "Eu prefiro mentir e criar uma farsa escandalosa do que admitir uma verdade que me faca parecer comum ou chato.",
      "Eu tenho uma divida enorme com alguem perigoso porque gastei tudo o que ganhei em uma unica noite de excessos.",
    ],
  },
  folk_hero: {
    personalityTraits: [
      "Eu julgo as pessoas pelas suas acoes, nao pelas suas palavras ou promessas.",
      "Se alguem estiver em apuros, eu nunca vou virar as costas ou recusar ajuda.",
      "Quando decido fazer algo, eu vou ate o fim, nao importa quantos obstaculos aparecam.",
      "Eu sou muito direto e sincero; nao tenho paciencia para a falsidade ou os jogos politicos dos nobres.",
      "Eu tenho um orgulho imenso da minha terra natal e do meu povo, e falo disso com frequencia.",
      "Eu sou uma pessoa comum, nao me coloco acima de ninguem e nao gosto de ser tratado como uma celebridade.",
      "Eu uso termos simples, analogias sobre a vida no campo ou ditados populares para explicar minhas ideias.",
      "Eu nao me assusto facilmente com ameacas, monstros ou tiranos; ja vi muita coisa dificil na vida real.",
    ],
    ideals: [
      "Respeito: As pessoas merecem ser tratadas com dignidade e respeito, independentemente de sua classe social. (Bom)",
      "Justica: A lei deve ser aplicada igualmente para todos, punindo os tiranos e protegendo os fracos. (Leal)",
      "Liberdade: Ninguem deve ser escravizado, oprimido ou forcado a obedecer a tiranos injustos. (Caotico)",
      "Poder: Se eu conseguir liderar o povo, poderei derrubar os governantes e assumir o controle do meu proprio destino. (Mau)",
      "Destino: Eu nao escolhi essa vida de heroi, mas o destino me colocou aqui e eu preciso cumprir o meu papel. (Neutro)",
      "Sinceridade: O mais importante e ser fiel aos seus proprios principios e nunca trair aqueles que confiam em voce. (Qualquer)",
    ],
    bonds: [
      "Eu daria a minha vida para proteger os moradores da vila ou comunidade onde cresci.",
      "Um tirano local destruiu minha antiga casa e perseguia meu povo; minha missao e conseguir justica ou vinganca.",
      "Eu trago comigo uma ferramenta ou um amuleto que pertenceu a pessoa que me inspirou a me erguer contra a opressao.",
      "Eu tenho uma divida de gratidao com a pessoa comum que me escondeu das autoridades quando eu era um fugitivo.",
      "Tudo o que eu faco e para provar que uma pessoa comum pode realizar grandes feitos e mudar o mundo.",
      "Minha familia nao sabe onde estou ou o que estou enfrentando, e eu luto para poder voltar em seguranca para eles.",
    ],
    flaws: [
      "Eu confio demais nas aparencias de outras pessoas comuns e posso ser facilmente enganado por um traidor disfarcado.",
      "Eu tenho um rancor profundo e destrutivo contra qualquer um que tenha autoridade ou titulo de nobreza.",
      "Eu me sinto na obrigacao de resolver os problemas de todo mundo, o que me faz assumir riscos desnecessarios.",
      "Eu tenho medo de que as pessoas descubram que eu sou apenas um campones comum e que meu grande feito foi sorte.",
      "Eu tenho dificuldades para aceitar a ajuda de outras pessoas, achando que preciso carregar o fardo sozinho.",
      "Minha teimosia e tao grande que prefiro quebrar a cara a admitir que o plano de outra pessoa era melhor que o meu.",
    ],
  },
  guild_artisan: {
    personalityTraits: [
      "Eu sou incrivelmente orgulhoso do meu trabalho e nao aceito que digam que outra pessoa faz melhor.",
      "Eu sou muito metodico e analiso tudo ao meu redor como se estivesse medindo materiais para uma construcao.",
      "Eu gosto de gastar meu dinheiro com o bom e o melhor, apreciando os frutos do meu trabalho arduo.",
      "Eu sou muito cooperativo e acredito piamente que o trabalho em equipe sempre supera o esforco individual.",
      "Eu tenho o habito de usar jargoes tecnicos do meu oficio mesmo quando estou conversando com leigos.",
      "Eu nao tenho paciencia com pessoas que fazem um trabalho malfeito ou demonstram preguica.",
      "Eu sempre busco aprender novas tecnicas ou descobrir materiais raros para aprimorar minha profissao.",
      "Eu sou muito bom em negociar e barganhar; sei exatamente quanto vale cada moeda e cada pedaco de ferro.",
    ],
    ideals: [
      "Comunidade: E dever de todos os membros da guilda apoiar uns aos outros e fortalecer o comercio local. (Bom)",
      "Generosidade: Minhas habilidades e riquezas devem ser usadas para melhorar a vida da comunidade ao meu redor. (Bom)",
      "Lei: A organizacao, as regras da guilda e os contratos sao o que mantem a sociedade longe do caos. (Leal)",
      "Inovacao: As velhas tradicoes devem dar espaco a novos metodos, ideias e ferramentas mais eficientes. (Caotico)",
      "Ganancia: O unico motivo para eu aprimorar meu oficio e acumular o maximo de ouro e bens materiais possivel. (Mau)",
      "Aspiracao: Eu trabalho duro para subir nos ranques da guilda e me tornar um mestre renomado e respeitado por todos. (Qualquer)",
    ],
    bonds: [
      "A guilda onde aprendi meu oficio e a coisa mais importante do mundo para mim; farei tudo para protege-la.",
      "Eu devo tudo ao mestre artesao que me aceitou como aprendiz quando eu nao tinha nada na vida.",
      "Eu procuro criar uma obra-prima tao perfeita e lendaria que meu nome sera lembrado na historia do meu oficio.",
      "Meus parceiros de negocio ou socios foram passados para tras por um rival corrupto, e eu vou recuperar o que e nosso.",
      "Eu trago comigo as ferramentas do meu falecido mestre, e elas sao o meu bem mais precioso e sagrado.",
      "Tudo o que eu lucro e enviado para garantir que minha familia possa abrir o proprio negocio no futuro.",
    ],
    flaws: [
      "Eu sou ganancioso ao extremo; se houver a menor chance de lucro ou de conseguir ouro, eu mudo minhas prioridades.",
      "Eu sou arrogante e julgo as pessoas pela qualidade de suas roupas, armas ou posses materiais.",
      "Eu prefiro seguir regras antigas e burocraticas da guilda do que fazer a coisa certa ou usar o bom senso.",
      "Eu nao consigo guardar segredos comerciais; se alguem elogiar meu trabalho, acabo revelando tecnicas valiosas.",
      "Eu tenho uma inveja profunda de qualquer artesao que consiga mais destaque ou clientes do que eu.",
      "Minha obsessao pelo trabalho e pela perfeicao me faz esquecer de comer, dormir ou notar os perigos ao meu redor.",
    ],
  },
  hermit: {
    personalityTraits: [
      "Eu estou tao acostumado com a solidao que as vezes esqueco de falar ou prefiro me comunicar por gestos.",
      "Eu sou calmo e reflexivo; pondero cada palavra demoradamente antes de responder.",
      "O mundo natural, os animais e o silencio me trazem muito mais conforto do que a multidao de uma cidade.",
      "Eu tenho o habito de falar sozinho ou responder aos meus proprios pensamentos em voz alta.",
      "Eu encaro cada evento, por menor que seja, como um sinal, pressagio ou reflexo de uma ordem maior.",
      "Eu nao me importo com convencoes sociais, boas maneiras ou a etiqueta que as pessoas da cidade exigem.",
      "Eu sou muito paciente e acredito que tudo na vida tem o seu tempo certo para florescer ou acabar.",
      "Eu guardo pensamentos profundos sobre o universo e costumo usar metaforas complexas que os outros nao entendem.",
    ],
    ideals: [
      "Conhecimento: A busca pela verdade, pela sabedoria e pelo autoconhecimento esta acima de tudo. (Neutro)",
      "Autoaperfeicoamento: O objetivo da vida e purificar o corpo, a mente e o espirito atraves da disciplina. (Qualquer)",
      "Provedor: Minhas descobertas e visoes devem ser compartilhadas para guiar e ajudar os necessitados. (Bom)",
      "Logica: As emocoes e os dogmas nao devem nublar nossa visao sobre a verdade dos fatos. (Leal)",
      "Autonomia: Ninguem deve depender de deuses, reis ou sociedades para descobrir quem realmente e. (Caotico)",
      "Isolamento: O mundo exterior esta corrompido e cheio de distracoes; a verdadeira paz so existe no isolamento. (Mau)",
    ],
    bonds: [
      "Eu entrei em isolamento para proteger um segredo terrivel que, se cair em maos erradas, destruira o mundo.",
      "Eu busco uma resposta ou uma cura para a visao terrivel que me assombrou durante meus anos de solidao.",
      "Meu mentor ou mestre me deixou uma missao inacabada antes de partir, e eu preciso conclui-la.",
      "Eu sou o ultimo guardiao de um local sagrado, ruina antiga ou biblioteca esquecida que o mundo nao pode descobrir.",
      "Eu voltei ao convivio social apenas para proteger as pessoas que eu amo de uma grande ameaca que previ.",
      "Meu diario de reflexoes e minhas anotacoes de isolamento contem o trabalho da minha vida e nao podem ser perdidos.",
    ],
    flaws: [
      "Eu sou dogmatico ao extremo e acredito que a minha visao sobre o mundo e a unica verdade absoluta.",
      "Eu sinto uma desconfianca profunda de qualquer tecnologia, grande cidade ou avanco da sociedade moderna.",
      "Eu guardo pensamentos sombrios e secretos que me fazem questionar se realmente vale a pena salvar o mundo.",
      "Minha falta de tato social me faz dizer verdades duras e crueis sem me importar com os sentimentos dos outros.",
      "Eu fico paralisado ou extremamente ansioso quando estou cercado por multidoes ou barulho excessivo.",
      "Eu me recuso a quebrar meus habitos e rituais diarios de meditacao, mesmo que a situacao seja de vida ou morte.",
    ],
  },
  noble: {
    personalityTraits: [
      "Meu elogio e um presente de valor inestimavel, e eu nao o distribuo a qualquer um.",
      "Se alguem me insultar, eu respondo com um desprezo frio e guardo a ofensa para cobrar mais tarde.",
      "Eu me recuso a me misturar com a plebe ou a frequentar lugares que nao estejam a altura da minha classe.",
      "Eu sou incrivelmente polido e sigo a etiqueta e as boas maneiras a risca, nao importa a situacao.",
      "Eu encaro qualquer desafio ou perigo com uma postura imperturbavel e aristocratica.",
      "Eu faco questao de que todos saibam o meu nome, os meus titulos e a importancia da minha linhagem.",
      "Eu nao tenho o menor conhecimento sobre o valor das coisas comuns e gasto ouro sem pensar no amanha.",
      "Eu falo de forma pausada e eloquente, esperando que todos fiquem em silencio para me ouvir.",
    ],
    ideals: [
      "Respeito: E dever das classes mais baixas respeitar a nobreza, assim como e nosso dever governar com justica. (Leal)",
      "Responsabilidade: Minha posicao me da poder, mas tambem o dever de proteger e guiar os menos afortunados. (Bom)",
      "Independencia: Minha familia que se dane; eu vou conquistar minhas proprias terras e meu proprio titulo. (Caotico)",
      "Poder: O sangue azul que corre em minhas veias me da o direito de governar e subjugar os mais fracos. (Mau)",
      "Familia: A linhagem e a reputacao da minha casa nobre estao acima de qualquer desejo individual. (Qualquer)",
      "Nobreza de Espirito: O verdadeiro valor de um nobre nao vem de seus titulos, mas de suas acoes e carater. (Bom)",
    ],
    bonds: [
      "Eu farei qualquer coisa para recuperar as terras, o titulo e a fortuna que foram roubados da minha familia.",
      "Eu sou o herdeiro direto da minha casa e carrego o fardo de perpetuar o nome e o legado dos meus antepassados.",
      "Eu estou apaixonado por alguem cuja classe social torna nosso relacionamento um escandalo proibido.",
      "Minha lealdade pertence ao soberano (rei, rainha ou duque) que concedeu os titulos e as honras a minha familia.",
      "Eu carrego uma reliquia de familia (um anel de sinete ou uma espada antiga) que prova a minha legitimidade.",
      "Eu busco vinganca contra a casa nobre rival que planejou a ruina e a desonra dos meus pais.",
    ],
    flaws: [
      "Eu acredito piamente que as pessoas comuns sao inferiores e nao merecem a minha atencao ou simpatia.",
      "Eu tenho um orgulho cego e prefiro morrer ou falhar a admitir que cometi um erro ou que fui derrotado.",
      "Eu mudo de humor drasticamente se nao receber o tratamento luxuoso e a deferencia que julgo merecer.",
      "Eu sou facilmente manipulado por elogios falsos e bajuladores que inflam o meu ego.",
      "Eu escondo um segredo escandaloso sobre o meu passado que arruinaria o nome da minha familia se fosse revelado.",
      "Eu subestimo completamente qualquer inimigo que nao venha de uma linhagem nobre ou que nao tenha posses.",
    ],
  },
  outlander: {
    personalityTraits: [
      "Eu sou guiado pelos meus instintos e sinto um desconforto profundo quando estou cercado por paredes de pedra e multidoes.",
      "Eu tenho uma grande dificuldade em entender o conceito de propriedade privada e o acumulo de ouro da cidade.",
      "Eu mudo de humor tao rapido quanto o clima da floresta, passando da calmaria a furia em segundos.",
      "Eu sou muito observador e costumo ficar em silencio, estudando o comportamento de todos ao meu redor.",
      "Eu prefiro agir a falar; a vida na natureza me ensinou que palavras nao sobrevivem ao inverno.",
      "Eu nao tenho o menor conhecimento ou paciencia para a etiqueta social, jantares formais ou a politica urbana.",
      "Eu honro os costumes da minha tribo ou do meu povo e faco questao de segui-los, nao importa onde eu esteja.",
      "Eu sou incrivelmente resistente e encaro qualquer desconforto fisico, fome ou frio com total indiferenca.",
    ],
    ideals: [
      "Mudanca: A natureza esta em constante mudanca e evolucao, e nos devemos mudar junto com ela. (Caotico)",
      "Equilibrio: A vida e a morte, o dia e a noite; tudo deve coexistir em perfeita harmonia no mundo. (Neutro)",
      "Proteger: E dever dos fortes proteger a terra e as criaturas que nao podem se defender sozinhas. (Bom)",
      "Gloria: O unico objetivo da vida e realizar grandes feitos na cacada ou na guerra para ser lembrado pelo meu povo. (Qualquer)",
      "Forca: Os fracos morrem e os fortes sobrevivem; a natureza nao tem espaco para a piedade. (Mau)",
      "Honra: Trair a sua tribo, sua palavra ou quebrar um pacto de sangue e o pior crime que alguem pode cometer. (Leal)",
    ],
    bonds: [
      "Minha tribo ou meu cla foi massacrado por monstros ou invasores, e eu vivo para vingar a morte deles.",
      "Eu trago comigo um amuleto ou uma reliquia da minha terra natal que me conecta aos espiritos dos meus ancestrais.",
      "Eu fui exilado do meu povo por um crime que nao cometi, e preciso provar o meu valor para poder retornar.",
      "Eu sou o ultimo sobrevivente de uma linhagem ou de um povo esquecido, e preciso garantir que nossa cultura nao morra.",
      "Eu tenho uma ligacao espiritual profunda com um animal sagrado ou um local da natureza que jurei proteger.",
      "Tudo o que eu aprendo e conquisto no mundo exterior e para ajudar a minha comunidade a sobreviver em tempos dificeis.",
    ],
    flaws: [
      "Eu tenho um preconceito profundo contra os povos civilizados e os considero fracos, moles e covardes.",
      "Se as coisas ficarem dificeis em um grupo, meu primeiro instinto de sobrevivencia e me salvar e deixar os outros para tras.",
      "Eu me irrito facilmente com a tecnologia, a magia complexa ou qualquer coisa que eu nao consiga entender.",
      "Minha violencia e explosiva; eu prefiro resolver desentendimentos com os punhos ou armas antes de tentar conversar.",
      "Eu sou extremamente supersticioso e posso me recusar a agir se notar um mau pressagio na natureza.",
      "Eu trago comigo uma divida de sangue com um cacador rival ou uma criatura antiga que esta me perseguindo.",
    ],
  },
  sage: {
    personalityTraits: [
      "Eu uso palavras complexas e jargoes academicos para explicar coisas extremamente simples.",
      "Eu sou incrivelmente curioso e leio absolutamente tudo o que cai nas minhas maos, desde tomos antigos a panfletos de rua.",
      "Eu passei tanto tempo entre livros que as vezes esqueço de cuidar da minha aparencia ou das boas maneiras.",
      "Eu adoro debates intelectuais e nao consigo resistir a oportunidade de corrigir alguem que esteja errado.",
      "Eu encaro o mundo com ceticismo e preciso de provas ou fatos documentados antes de acreditar em qualquer coisa.",
      "Eu sou muito calmo e concentrado, capaz de passar dias inteiros focado na resolucao de um unico enigma ou misterio.",
      "Eu vivo no mundo das ideias e costumo me distrair facilmente com pensamentos profundos no meio de uma conversa.",
      "Eu valorizo o conhecimento acima das pessoas; um livro raro vale muito mais para mim do que a opiniao de um leigo.",
    ],
    ideals: [
      "Conhecimento: A busca pela verdade e pelo aprendizado e o objetivo mais nobre que alguem pode ter na vida. (Neutro)",
      "Logica: As emocoes e os preconceitos nao devem nublar nosso julgamento sobre a verdade e a ciencia. (Leal)",
      "Compartilhar: O conhecimento nao deve ser trancado em torres; ele pertence ao povo e deve ser usado para o bem de todos. (Bom)",
      "Poder: O conhecimento e a chave para desvendar os segredos do universo e controlar o destino dos outros. (Mau)",
      "Autoaperfeicoamento: Estudar e a unica forma de expandir a mente e alcancar todo o potencial do meu ser. (Qualquer)",
      "Quebra de Dogmas: A verdade so pode ser encontrada quando questionamos as velhas leis e as tradicoes cegas. (Caotico)",
    ],
    bonds: [
      "Eu dediquei a minha vida a proteger uma biblioteca antiga, universidade ou ordem de estudiosos a qual pertenco.",
      "Eu trago comigo o diario ou as anotacoes inacabadas do meu falecido mestre, e minha missao e concluir seu trabalho.",
      "Existe um enigma antigo ou um texto traduzido pela metade que eu preciso decifrar a todo custo.",
      "Meus rivais academicos roubaram o trabalho da minha vida e o publicaram como se fosse deles; eu vou provar a fraude.",
      "Tudo o que eu busco e descobrir a verdade por tras de um evento historico ou catastrofe que destruiu o meu passado.",
      "Eu busco o conhecimento para salvar alguem que amo de uma maldicao antiga ou de uma doenca desconhecida.",
    ],
    flaws: [
      "Eu sou extremamente arrogante e secretamente acredito que todos que nao sao academicos sao ignorantes e inferiores.",
      "Quando me deparo com um texto antigo, mapa ou reliquia historica, eu esqueço completamente do perigo ao meu redor.",
      "Eu prefiro passar horas procurando respostas em um livro antigo do que agir ou tomar uma decisao rapida na vida real.",
      "Eu guardo um segredo ou uma descoberta heretica que, se revelada, me faria ser expulso do mundo academico.",
      "Eu sou facilmente distraido por teorias da conspiracao e enigmas, mesmo que eles nao tenham nenhuma utilidade pratica.",
      "Minha teimosia intelectual e tao grande que eu prefiro manter um argumento errado a admitir que perdi um debate.",
    ],
  },
  sailor: {
    personalityTraits: [
      "Minha linguagem e tao aspera quanto o mar, e eu uso expressoes de marinheiro e palavroes com frequencia.",
      "Eu tenho uma resistencia incrivel para o trabalho duro e encaro tempestades ou privacoes sem reclamar.",
      "Eu adoro contar historias exageradas sobre monstros marinhos, terras distantes e tempestades historicas.",
      "Eu faco amigos rapidamente em qualquer taverna ou porto onde desembarco, bebendo com quem estiver por perto.",
      "Eu sou muito supersticioso e vejo pressagios em tudo, desde a cor das nuvens ate o comportamento das gaivotas.",
      "Eu nao me sinto confortavel em lugares fechados e silenciosos; prefiro o barulho do vento e o balanco das ondas.",
      "Eu sou extremamente leal aos meus companheiros de tripulacao e nunca deixo um aliado para tras.",
      "Eu estudei as estrelas e as correntes maritimas, e confio mais no meu senso de direcao do que em mapas de papel.",
    ],
    ideals: [
      "Respeito: O respeito e a confianca mutua sao o que mantem uma tripulacao viva no meio do oceano. (Leal)",
      "Liberdade: O mar representa a liberdade total, longe das leis sufocantes e dos impostos dos reis da terra firme. (Caotico)",
      "Companheirismo: Nos navegamos juntos e sobrevivemos juntos; um marinheiro deve sempre apoiar o outro. (Bom)",
      "Ganancia: Eu sigo o navio que prometer o maior saque, o ouro mais facil e os saques mais valiosos. (Mau)",
      "Destino: O mar e uma forca implacavel e incontrolavel; nos apenas seguimos o rumo que ele decide nos dar. (Neutro)",
      "Aspiracao: Um dia eu terei o meu proprio navio e serei o capitao mais respeitado e temido de todos os oceanos. (Qualquer)",
    ],
    bonds: [
      "Minha lealdade pertence ao capitao e a tripulacao do meu antigo navio, que se tornaram a minha verdadeira familia.",
      "Eu trago comigo um mapa ou uma pista que leva a um tesouro lendario enterrado em uma ilha esquecida.",
      "Eu busco vinganca contra os piratas ou o monstro marinho que destruiu o meu navio e matou meus companheiros.",
      "Eu tenho uma divida enorme com o dono de um estaleiro ou taverna de porto, e preciso pagar para limpar meu nome.",
      "Eu navego para mandar moedas para a minha familia ou para um amor que ficou me esperando no meu porto de origem.",
      "Eu quebrei uma lei grave no mar ou cometi um motim, e estou sempre fugindo das autoridades navais.",
    ],
    flaws: [
      "Eu nao consigo resistir aos prazeres da terra firme, gastando todo o meu ouro em bebida e apostas assim que desembarco.",
      "Eu prefiro resolver qualquer desentendimento com uma briga de taverna ou um duelo de laminas antes de tentar conversar.",
      "Eu sou arrogante e acredito que qualquer pessoa que nao saiba navegar ou pescar e fraca e inutil.",
      "Minha supersticao e tao forte que posso entrar em panico ou me recusar a agir se notar um mau pressagio.",
      "Eu tenho uma dificuldade enorme em obedecer a autoridades em terra firme, como guardas, juizes ou nobres.",
      "Eu guardo um segredo sombrio sobre um naufragio onde eu me salvei, mas deixei outros para tras para morrerem.",
    ],
  },
  soldier: {
    personalityTraits: [
      "Eu sou sempre disciplinado e mantenho minha postura, minhas armas limpas e minhas botas polidas.",
      "Eu trago comigo a rigidez da vida militar e costumo encarar tudo como uma missao a ser cumprida.",
      "Eu tenho historias de batalhas para absolutamente qualquer situacao ou conversa que surja.",
      "Eu sou muito protetor com os meus companheiros e assumo a lideranca do grupo sempre que o perigo aparece.",
      "Eu perdi muitos amigos na guerra e, por isso, sou fechado e demoro a confiar em novas pessoas.",
      "Eu tenho um respeito profundo pela hierarquia e costumo obedecer a ordens sem questionar, desde que venham de um superior.",
      "Eu encaro o perigo com uma calma fria, fruto de anos encarando a morte nos campos de batalha.",
      "Eu uso jargões militares, termos de estrategia e analogias de combate para explicar minhas ideias cotidianas.",
    ],
    ideals: [
      "Maior Bem: Nosso dever e dar a vida para proteger aqueles que nao podem se defender sozinhos. (Bom)",
      "Disciplina: A ordem, a obediencia e a estrutura sao as unicas coisas que separam a civilizacao do caos da guerra. (Leal)",
      "Independencia: A guerra me ensinou que as ordens dos generais nem sempre sao certas; eu sigo minha propria consciencia. (Caotico)",
      "Poder: No campo de batalha, apenas os fortes sobrevivem e ditam as regras; a forca e a unica verdade. (Mau)",
      "Nacao: Minha espada, meu escudo e minha vida pertencem ao meu povo e ao meu reino, acima de tudo. (Neutro)",
      "Gloria: Eu luto para que meu nome seja lembrado nas musicas, nos livros de historia e para alcancar a fama eterna. (Qualquer)",
    ],
    bonds: [
      "Eu daria a minha vida sem hesitar para proteger os soldados que lutaram ao meu lado no mesmo esquadrao.",
      "Eu busco vinganca contra o general traidor ou o inimigo de guerra que massacrou meus companheiros em uma emboscada.",
      "Eu trago comigo uma medalha de honra ou um pedaco do estandarte do meu antigo batalhao, e ele e meu bem mais sagrado.",
      "Tudo o que eu faco e para honrar a memoria do meu mentor ou oficial superior que morreu para me salvar.",
      "Eu luto para garantir que a minha familia, que ficou na minha terra natal, nunca precise passar pelos horrores da guerra.",
      "Eu tenho uma divida de sangue com um soldado inimigo que poupou a minha vida no campo de batalha, e um dia vou retribuir.",
    ],
    flaws: [
      "Eu tenho um desprezo profundo por civis e pessoas que nunca pegaram em uma arma para defender seu povo.",
      "Eu sofro com as memorias da guerra; certos barulhos, cheiros ou situacoes me fazem entrar em panico ou congelar.",
      "Eu sigo ordens de forma tao cega que posso cometer atos crueis ou injustos apenas porque um superior mandou.",
      "Eu sou arrogante e acredito que a forca militar e a violencia sao as unicas formas eficientes de resolver qualquer problema.",
      "Eu guardo um rancor destrutivo contra o reino ou a raca inimiga contra quem lutei no passado, nao importa as circunstancias.",
      "Eu prefiro morrer em um combate suicida a recuar ou admitir uma derrota tática diante do inimigo.",
    ],
  },
  urchin: {
    personalityTraits: [
      "Eu escondo comida nos meus bolsos sempre que posso, com medo de nao ter o que comer amanha.",
      "Eu nao confio em ninguem que use roupas limpas ou que fale de forma muito educada.",
      "Eu conheco os becos, esgotos e telhados da cidade como a palma da minha mao e me movo por eles sem fazer barulho.",
      "Eu sou muito esperto e uso piadas, deboche ou ironia para esconder o medo que sinto por dentro.",
      "Eu durmo com um olho aberto e com a mao na minha arma ou na minha bolsa de moedas.",
      "Eu nao tenho modos a mesa e costumo comer rapido, como se alguem fosse roubar o meu prato a qualquer segundo.",
      "Eu sou muito observador e sei exatamente quem e a pessoa mais perigosa ou o elo mais fraco de qualquer grupo.",
      "Eu sou extremamente leal aos poucos amigos que conquistaram minha confianca, pois sei como e estar sozinho.",
    ],
    ideals: [
      "Respeito: Todos os seres vivos, por mais pobres ou desprezados que sejam, merecem dignidade. (Bom)",
      "Comunidade: Nos, os esquecidos das ruas, precisamos nos unir e cuidar uns dos outros para sobreviver. (Bom)",
      "Liberdade: Ninguem vai me trancar em uma cela, em um orfanato ou me dizer o que eu tenho que fazer. (Caotico)",
      "Vinganca: Os ricos e poderosos vao pagar por cada dia de fome e humilhacao que me fizeram passar. (Mau)",
      "Aspiracao: Eu vou subir na vida, acumular ouro e provar que um rato de rua pode se tornar um mestre ou um heroi. (Qualquer)",
      "Sobrevivencia: Leis, moral e honra nao enchem a barriga; eu farei o que for preciso para continuar vivo. (Neutro)",
    ],
    bonds: [
      "Eu trago comigo um pequeno objeto sem valor (um brinquedo quebrado, uma fita ou um anel de latao) que e minha unica lembranca dos meus pais.",
      "Eu devo a minha vida ao mestre dos ladroes ou ao idoso de rua que me acolheu e me ensinou a sobreviver nas calçadas.",
      "Eu divido tudo o que ganho com o grupo de criancas de rua ou com o orfanato onde cresci.",
      "Um guarda ou um nobre especifico arruinou a vida de todos que eu conhecia nas ruas, e eu vou acabar com ele.",
      "Eu procuro por meu irmao, irma ou amigo de infancia que foi levado de mim quando eramos pequenos.",
      "A cidade onde cresci e o meu lar; eu vou protege-la dos monstros ou da destruicao, nao importa o que aconteca.",
    ],
    flaws: [
      "Eu nao consigo resistir a oportunidade de bater a carteira de alguem que pareca rico e arrogante, mesmo se for perigoso.",
      "Eu sou extremamente covarde quando o perigo e desconhecido ou magico; meu primeiro instinto e correr e me esconder.",
      "Eu minto compulsivamente sobre o meu passado para evitar que as pessoas descubram minhas fraquezas ou de onde vim.",
      "Eu sou muito orgulhoso e recuso qualquer tipo de caridade ou ajuda sincera, achando que estao me humilhando.",
      "Eu guardo um rancor profundo contra qualquer pessoa que me trate com desdem ou que ignore a minha presenca.",
      "Se as coisas ficarem realmente feias, eu coloco a minha propria sobrevivencia acima da vida dos meus companheiros.",
    ],
  },
};

const getBackgroundFieldTable = (
  backgroundId: string,
  field: CreationRandomizableField,
): string[] => {
  const normalizedId = normalizeBackgroundId(backgroundId);
  return BACKGROUND_RANDOM_TABLES[normalizedId]?.[field] ?? [];
};

export const getBackgroundRandomOptions = (
  backgroundId: string,
  field: CreationRandomizableField,
): string[] => getBackgroundFieldTable(backgroundId, field);

export const hasBackgroundRandomOptions = (
  backgroundId: string,
  field: CreationRandomizableField,
): boolean => getBackgroundFieldTable(backgroundId, field).length > 0;

export const rollBackgroundRandomOption = (
  backgroundId: string,
  field: CreationRandomizableField,
  rng: () => number = Math.random,
): string | null => {
  const options = getBackgroundFieldTable(backgroundId, field);
  if (options.length === 0) {
    return null;
  }

  const index = Math.min(options.length - 1, Math.floor(rng() * options.length));
  return options[index] ?? null;
};
