export const routes = {
  root: "/",
  home: "/home",
  gmHome: "/home/gm",
  playerHome: "/home/player",
  login: "/login",
  register: "/register",
  join: "/join",
  campaignHome: "/campaign",
  campaigns: "/campaigns",
  campaignDetails: "/campaigns/:campaignId",
  campaignSessions: "/campaigns/:campaignId/sessions",
  gmDashboard: "/campaigns/:campaignId/dashboard",
  board: "/board/:campaignId",
  shop: "/shop",
  catalog: "/catalog",
  inventory: "/inventory",
  npcs: "/npcs",
  rolls: "/rolls",
} as const;
