export {
  CastingTimeType,
  ResolutionType,
  SaveSuccessOutcome,
  SpellAttackType,
  SpellDamageType,
  SpellEffectTiming,
  SpellOriginType,
  SpellRangeKind,
  SpellSavingThrow,
  SpellSchool,
  SpellSelectionType,
  SpellSource,
  SpellTargetAnchor,
  AreaShape,
  TargetType,
  UpcastMode,
} from "./baseSpell.types";

export type {
  BaseSpell,
  BaseSpellAlias,
  BaseSpellFilters,
  BaseSpellWritePayload,
  SpellCantripScaling,
  SpellUpcast,
  SpellAttackType as SpellAttackTypeValue,
  SpellEffectTiming as SpellEffectTimingValue,
  SpellOriginType as SpellOriginTypeValue,
  SpellRangeKind as SpellRangeKindValue,
  SpellSelectionType as SpellSelectionTypeValue,
  SpellTargetAnchor as SpellTargetAnchorValue,
} from "./baseSpell.types";
